# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/WorkPrograms/git-projects/srsRAN_4G/fpga/lte_phy_math_core/vivado/lte_phy_math_core.srcs/sources_1/ip/dsp_xilinx_macro/dsp_xilinx_macro.xci
# IP: The module: 'dsp_xilinx_macro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/WorkPrograms/git-projects/srsRAN_4G/fpga/lte_phy_math_core/vivado/lte_phy_math_core.gen/sources_1/ip/dsp_xilinx_macro/dsp_xilinx_macro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_xilinx_macro'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/WorkPrograms/git-projects/srsRAN_4G/fpga/lte_phy_math_core/vivado/lte_phy_math_core.srcs/sources_1/ip/dsp_xilinx_macro/dsp_xilinx_macro.xci
# IP: The module: 'dsp_xilinx_macro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/WorkPrograms/git-projects/srsRAN_4G/fpga/lte_phy_math_core/vivado/lte_phy_math_core.gen/sources_1/ip/dsp_xilinx_macro/dsp_xilinx_macro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_xilinx_macro'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
